### ISSUE TITLE
Release as free software

### ISSUE THREAD

**Issue by DWagenk** [hmr-it/kimai2-offline-tracker-app#5]
Hey. I'm using kimai2 mostly, because it's free/open souece software and I can self host it. Would be great to have the app as free software as well!

PS: you would still be able to charge for it on play store. Basically nobody will build an app from source to circumvent paying a few bucks for it on play store. There's also some open source apps that are available as paid apps via the play store but for free via the f-droid store (e.g. DAVx5)

**Comment by hmr-it-jr** [comment]
Hey, currently we don't have any plans to make this app open source.

**Comment by DWagenk** [comment]
Well, I won't ever be using it then. Best wishes
